export default {
    ON_UPDATE_CATEGORY_AND_SUBCATEGORY_ID_CHANGE: 'ON_UPDATE_CATEGORY_AND_SUBCATEGORY_ID_CHANGE',
    ON_DASHBOARD_FILINGS_UPLOAD_FORM_CHANGE : 'ON_DASHBOARD_FILINGS_UPLOAD_FORM_CHANGE',
    ON_UPLOAD_FORM_CASE_TYPE_CHANGE: 'ON_UPLOAD_FORM_CASE_TYPE_CHANGE',
    ON_UPLOAD_FORM_FISCAL_YEAR_CHANGE: 'ON_UPLOAD_FORM_FISCAL_YEAR_CHANGE',
    ON_UPLOAD_FORM_DURATION_FROM_CHANGE: 'ON_UPLOAD_FORM_DURATION_FROM_CHANGE',
    ON_UPLOAD_FORM_DURATION_TO_CHANGE: 'ON_UPLOAD_FORM_DURATION_TO_CHANGE',
    ON_UPLOAD_FORM_NOTE_DETAILS : 'ON_UPLOAD_FORM_NOTE_DETAILS',
    ON_UPLOAD_FORM_FILE_UPLOAD: 'ON_UPLOAD_FORM_FILE_UPLOAD',
    ON_FILE_UPLOAD_ID : 'ON_FILE_UPLOAD_ID',
    RESET : 'RESET'
}