export default {
    ON_UPLOAD_FORM_DETAILS : 'ON_UPLOAD_FORM_DETAILS',
    ON_MODAL_REJECTION_REASON_UPDATE : 'ON_MODAL_REJECTION_REASON_UPDATE',
    ON_DASHBOARD_UPLOADS_VIEW_CLICKED: 'ON_DASHBOARD_UPLOADS_VIEW_CLICKED',
    ON_UPDATE_FORM_STATUS : 'ON_UPDATE_FORM_STATUS',
    ON_EDIT_FORM_DURATION_FROM_CHANGE: 'ON_EDIT_FORM_DURATION_FROM_CHANGE',
    ON_EDIT_FORM_FISCAL_YEAR_CHANGE: 'ON_EDIT_FORM_FISCAL_YEAR_CHANGE',
    ON_EDIT_FORM_DURATION_TO_CHANGE: 'ON_EDIT_FORM_DURATION_TO_CHANGE',
    ON_EDIT_FORM_NOTE_DETAILS : 'ON_EDIT_FORM_NOTE_DETAILS',
    ON_EDIT_FORM_FILE_UPLOAD: 'ON_EDIT_FORM_FILE_UPLOAD',
    ON_FILE_UPLOAD_ID : 'ON_FILE_UPLOAD_ID',
    ON_EDIT_BUTTON_CLICKED:'ON_EDIT_BUTTON_CLICKED'
}