export default {
    ON_DETAILS_CHANGE : ' ON_DETAILS_CHANGE',
    ON_SUBMENU_OPEN:'ON_SUBMENU_OPEN',
    ON_SUBMENU_SELECTED:'ON_SUBMENU_SELECTED',
    ON_MENU_SELECTED:'ON_MENU_SELECTED',
    ON_USER_ENTER:'ON_USER_ENTER'
}