export default {
    ON_NEW_PASSWORD_CHANGE : ' ON_NEW_PASSWORD_CHANGE',
    ON_REENTERD_NEW_PASSWORD_CHANGE : 'ON_REENTERD_NEW_PASSWORD_CHANGE',
    ON_PASSWORD_NOT_MATCHED : ' ON_PASSWORD_NOT_MATCHED',
    ON_RESET:'ON_RESET'
}