export default {
    ON_UPDATE_UPLODE_LIST_DETAILS : 'ON_UPDATE_UPLODE_LIST_DETAILS',
    ON_UPDATE_MYUPLODE_LIST_DETAILS : 'ON_UPDATE_MYUPLODE_LIST_DETAILS',
    ON_UPDATE_ALLUPLODE_LIST_DETAILS : 'ON_UPDATE_ALLUPLODE_LIST_DETAILS',
    
    ON_ALLUPLOAD_PAGINATION:'ON_ALLUPLOAD_PAGINATION',
    ON_MYUPLOAD_PAGINATION:'ON_MYUPLOAD_PAGINATION',
    ON_ALLUPLOAD_CHECKBOX_CHANGE:'ON_ALLUPLOAD_CHECKBOX_CHANGE',
    ON_MYUPLOAD_CHECKBOX_CHANGE:'ON_MYUPLOAD_CHECKBOX_CHANGE',
    ON_RESET_PAGINATION:'ON_RESET_PAGINATION',
    UPLOAD_TABLE_LOADING_STATUS:'UPLOAD_TABLE_LOADING_STATUS',

    My_TABLE_LOADING_STATUS:'My_TABLE_LOADING_STATUS',
    All_TABLE_LOADING_STATUS:'All_TABLE_LOADING_STATUS',
    ON_ALLUPLOAD_Checked:'ON_ALLUPLOAD_Checked',
    ON_MYUPLOAD_Checked:'ON_MYUPLOAD_Checked',
    ON_ALLUPLOAD_PAGINATION_CLICKED:'ON_ALLUPLOAD_PAGINATION_CLICKED',
    ON_MYUPLOAD_PAGINATION_CLICKED:'ON_MYUPLOAD_PAGINATION_CLICKED'
}
